### ISSUE TITLE
Question Only About How Leading Edge Wing Slat is Modeled

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/wilga#11]
@krzysk1 I have a question regarding if and how the effects of the Wilga's continuous leading edge wing slat is modeled in Aerofly FS. The reason I ask is because it still seems to me that the Wilga has to fly too fast to maintain altitude. I understand that most online references state that it uses a NACA 2425 airfoil (but maybe this really is for the PZL Wilga 2000 only?), although I have seen a scale model PZL 104 35 spec that uses a NACA 4412 airfoil (which has more lift) which is odd since scale models generally use the same airfoil as the real aircraft. I am just wondering if it is possible that Aerofly FS does not model leading edge wing slat like the Wilga has and if an additional amount should be added to Cl0 to simulate this?
https://icare-icarus.3dcartstores.com/Wilga-35-24m_p_1224.html
https://scalesoaring.co.uk/wilga/
NACA 4412 Cl0 0.50 Cd0 0.08 Cm0 -0.103
http://airfoiltools.com/polar/details?polar=xf-naca4412-il-1000000
NACA 2415 Cl0 0.25 Cd0 0.07 Cm0 -0.051
http://airfoiltools.com/polar/details?polar=xf-n2415-il-1000000

**Comment by jayeye2011** [comment]
Here is a tmd file version that uses NACA 4412 airfoil and has adjustments to wing, horizontal and vertical stabilizer propwashpercentage and propwashrotation that as neutral roll tendency and maintains level flight at 77 to 76 kias with 0 elevator trim.
[wilga_tmd.zip](https://github.com/krzysk1/wilga/files/10365446/wilga_tmd.zip)
![20230106193202_1](https://user-images.githubusercontent.com/69315126/211129681-bcb9efd0-34ff-4d74-bcb5-45b504c8c9d6.jpg)

**Comment by krzysk1** [comment]
Wilga was created in AeroflyFS2 first and there was no separate parameter for slats, so you need to use airfoil parameters only to simulate slat efect. In Aerofly FS4 there are some new objects available: airfoil2 and aerowing2 that have much more parameters, among them slat related - see b737 as example.  I don't know much about new features and I've not used them in my convertion yet.

See also https://www.aerofly.com/community/forum/index.php?thread/18492-simulated-aerodynamic-stability/&postID=113164&highlight=aerowing#post113164

You are allowed to update TMD file directly in the repository if you consider that flight model is improved

**Comment by jayeye2011** [comment]
Actually this experimental NACA 4412 setup does not conform to the performance specification listed in the EU PZL104 Wilga 80 type certificate so I would not want it to be incorporated into your official version. With regard to the zeroing out of left roll tendency that is just my personal preference as a non-pilot casual simmer and would not be appropriate for those who want a more real experience. Consider this closed.

**Comment by jayeye2011** [comment]
@krzysk1 Thanks for the invites but I will have to decline because as you have no doubt noticed from the issues I have posted, I can have some pretty bad ideas about what is what and prefer to allow you to filter out anything stupid I bring up rather than inadvertently goof up something. Plus a lot of it is just personal preferences rather than trying to generate an accurate flight model. Thanks.

**Comment by jayeye2011** [comment]
Final comment to keep the record straight. The Wilga 80 real aircraft does use a NACA 2415 airfoil but with fixed leading edge slat across the whole wing. Because it is uncertain if or how the new Aerofly FS 4 tmd file fomat defines wing slats it is necessary to use a higher lift airfoil (NACA 4412)  to try to get a performance closer to the what a NACA 2415 with leading edge wing slats performance is. The NACA 4412 was chosen because it was used for a commercial scale model of the Wilga 80 which also does not replicate the real aircrafts leading edge wing slat. I recommend that when and if the Aerofly FS 4 TMD documentations indicates that it is possible to specifiy a continuous leading edge wing slat that the wilga.tmd file be updated to use the NACA 2415 airfoil specifications along with the wing slat parameters.
