### ISSUE TITLE
Thai Flying Club Wilga 80 Information including Checklist

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/wilga#17]
This is for information purposes only. In case you have not seen this, there is the Thai Flying Club website with information on the Wilga 80 including a Wilga Checklist (which lists V speeds!). Really wish there was a indicator for engine rpm or prop rpm.
http://www.thaiflyingclub.com/linkwilga.html
http://www.thaiflyingclub.com/linkwilgachecklist.html
http://www.thaiflyingclub.com/linkwilgaarticle.html
In case this site goes away some day here are pdfs of the relevant web pages
[PZL-104 _Wilga_ Checklist (abbreviated).pdf](https://github.com/krzysk1/wilga/files/10466129/PZL-104._Wilga_.Checklist.abbreviated.pdf)
[WILGA ARTICLE.pdf](https://github.com/krzysk1/wilga/files/10466131/WILGA.ARTICLE.pdf)
Maybe someday Wilga model can be more accurately tuned to reflect this information.

**Comment by krzysk1** [comment]
thanks for the references, saved.  I have access to manuals (in Polish :D )
