### ISSUE TITLE
Can not steer plane on ground taxi

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/wilga#2]
X-Plane 11 v11.53 (Steam) - the tail wheel does not move with rudder when trying to taxi on the ground so cannot turn the plane to follow taxi way also can not steer during takeoff before rotation so  you just run off the side of the pavement.

**Comment by jayeye2011** [comment]
The Aerofly FS 4 version of the Wilga still has the no tail wheel steering bug. This time to be more constructive, I read through the Aerofly FS Wiki about the TMD file structure dynamic objects section, specifically about rigid body Multibody-Joint connection. Comparing the Wilga.tmd file to the Dromader.tmd and the z526afs.tmd files I was able to determine that the following section stating at line 191 in the original Wilga.tmd file 
            <[multibody_joint][JointFuselageTailGear][]
                <[tmvector3d][X0][ 0.0 1.0 0.0]>
                <[float64][Kp][12000.0]>
                <[float64][Kd][1200.0]>
                <[string8][Body0][Fuselage]>
                <[string8][Body1][TailGear]>
                <[tmvector3d][R0][-5.0967 0.0 -0.3769]>
                <[uint32][Type][0]>
Is incomplete because it does not have a  X0 rotation axis defined and does not have a ServoSteering.Output definition.
to fix this you need to change the JointFuselageTailGear section to the following
            <[multibody_joint][JointFuselageTailGear][]
                <[tmvector3d][X0][ 0.0 1.0 0.0]>
                <[float64][Kp][12000.0]>
                <[float64][Kd][1200.0]>
                <[string8][Body0][Fuselage]>
                <[string8][Body1][TailGear]>
                <[tmvector3d][X0][ 0.0 0.0 1.0 ]>
                <[tmvector3d][R0][-5.0967 0.0 -0.3769]>
                <[uint32][Type][0]>
                <[string8][InputLock][1.0]>
                <[string8][InputPosition][ServoSteering.Output]>
Here is what full left rudder and full right rudder looks like with this correction

![20221202122632_1](https://user-images.githubusercontent.com/69315126/205381825-b8c09319-4a9c-4d61-95f4-989256f52802.jpg)
![20221202122628_2](https://user-images.githubusercontent.com/69315126/205381848-c72d53f7-a1a4-4feb-bcdf-526a9d0b1d14.jpg)
Here is the patched wilga.tmd file
[wilga tmd tailwheel steering patch.zip](https://github.com/krzysk1/wilga/files/10144159/wilga.tmd.tailwheel.steering.patch.zip)

**Comment by jayeye2011** [comment]
I believe this fix should also apply to the AF FS 2 Wilga version as I don't think the wiki was FS 4 specfic

**Comment by krzysk1** [comment]
I realised the steering control in a slightly different way: I used an additional rigidbody element for suspension and pivoting inclined according to the 3d model
