### ISSUE TITLE
Overly Responsive Elevator Trim

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/wilga#3]
Trying to trim out pitch for level flight is difficult due to extreme elevator trim response when tapping buttons assigned for trim up and trim down command. Looking at the wilga.tmd file I think there is a issue with the the ElevatorTrimInput[Positions] line because I compared it to your tomahawk.tmd settings and while the tomahawk uses ElevatorTrimInput{Positions][201] the wilga uses s ElevatorTrimInput{Positions][41] 
Wilga.tmd
            <[input_default][ElevatorTrimInput][]
                <[string8][Message][Controls.Trim]>
                <[uint][Positions][41]>
                <[tmvector2d][Range][ -1.0 1.0 ]>
                <[float64][Value][0.0]>
                <[float64][Speed][0.125]>
            >
Tomahawk.tmd
           <[input_default][ElevatorTrimInput][]
                <[string8][Message][Controls.Trim]>
                <[uint][Positions][201]>
                <[tmvector2d][Range][ -1.0 1.0 ]>
                <[float64][Value][0.0]>
                <[float64][Speed][0.125]>
            >

**Comment by krzysk1** [comment]
This does not affect the flight model. The number only indicates how many discrete positions the trimmer can take in the range of -1 to 1. A higher number makes it necessary to press more times to achieve a similar change, but more fine tuning can be done because steps are smaller
