### ISSUE TITLE
Rudder Ineffective

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/wilga#4]
Testing the rudder in the Wilga to see how it overcomes P-factor and how much it can effect aircraft bank angle, I seems to me that the rudder seems to have very little effect until you get to extreme rudder angles. I wonder if the there is an incorrect specification set in for the VerticalStabilizer section?
![20221209042314_1](https://user-images.githubusercontent.com/69315126/206702470-eb1bf5eb-f8b4-471c-8b8e-884e4b72329b.jpg)
The wilga.tmd file [aerowing][VertStabilizer1Aero][] section may have an issue with the StationFlap and StationFlapFraction  statements that define the rudder control surface, 
                <[uint32array][StationFlap]         [ 0 1 1 0 ]>
                <[float64array][StationFlapFraction][ 0.0 0.26 0.45 0.0 ]>
This seems a bit odd because the 3D model shows the rudder control surface extends across the full height of the vertical stabilizer, not just in the middle section.
![rudder surface](https://user-images.githubusercontent.com/69315126/206706526-4f371455-259e-45e2-9d97-4bb0208dedd9.jpg)

**Comment by krzysk1** [comment]
The rudder has been simplified, but this makes little difference to the flight model: the lowest 20 cm has been excluded (there is a narrower rudder there) and the top half has been overestimated (45% over the entire length when in reality this size is only at the very top) so the total area of the rudder surface is even overestimated. This can be corrected but will not significantly affect the model. More can be achieved by adjusting the vertical stabiliser profile 

i will change it as this:

<[uint32array][StationFlap] [ 1 1 1 1 0 ]>
<[float64array][StationFlapFraction][ 0.15 0.26 0.26 0.45 0.0 ]>

(last 0 is always not counted)
