### ISSUE TITLE
Thoughts Regarding Wing Dihedral and Incidence Angles

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/wilga#6]
I can't  find any direct specification of wing dihedral in the TMD file so I guess its defined by the aeroWing:StationZ array by means of z position vs station[n] StationY value. Seems like you not only have to find out what the spec dihedral is but then so inverse sine trig calculation.  Unfortunately who knows what the dihedral is supposed to be, I'll just assume you came up with a good number on this one. If you don't have a real world spec for dihedral, I would use enough to satisfy you esthetic on roll stability for maintaining level flight for the particular aircraft (i.e., BF-109E vs Piper Cub).
The wing incidence angle used seems a bit much to me though.
   <[aerowing][LeftWingAero][]
                <[float64array][StationIncidence]   [ 0.10472 0.10472 0.08727 0.08727 ]>
<[aerowing][LeftWing2Aero][]
                <[float64array][StationIncidence]   [ 0.08727 0.06981 ]>
Radians to degrees this is 6.0 6.0 5.0 5.0 degree and 5.0 4.0 degrees, so basically it looks like you start with 6 degrees on the inboard edge of the wing and non-uniformly going from 6.0 to 5.0  and end up with 4.0 degrees at the outboard tip of the wing?
This value makes the Wilga try to nose and climb at an extreme since the horizontal stabilizers have 0 degree incidence angles so no counter effect.  If you think finding out the wing dihedral spec for an aircraft is hard, let me tell you finding out the actual wing and horizontal stabilizer incidence angle specs is pretty much impossible. So with regard to incidence angles, I think that is more of a discretionary flight tuning parameter than a hard set value. The final values you decide to use for either should be influenced by what you want to have to use for elevator trim and airspeed when at level cruise altitude.  Horizontal stabilizer incidence angle can sometimes be used to counter the effects that main wing incidence angle has on aircraft attitude and also introduce an negative feedback loop input that can prevent or reduce level flight porpoising effect. In X-Plane when people want to use wing washout they start with the full initial incidence angle on the inboard part of the wing and gradually reduce it to zero at the wing tip over however many wing-blade elements (usually 4 to 10)  they use for the left wing definition in the ACF file.  If you are not going for a washout effect (not even sure Aerofly FS can actually simulate this) then why not keep it simple and use the same incidence angle on all stations.
As an example setting Left and Right Wing Aero 1 and 2 to uniform incidence angle of 3.5 degrees (about 0.06108) radians and leaving Left and Right horizontal Stabilizer at 0 degrees incidence  resulted in this (with some aileron right trim) somewhat stable level flight using 0 elevator trim at 46% throttle, 98kts and 2960 feet.  Not sure if that cruise speed is what you want or not since it seems to be in the yellow zone on the info display.
![20221210062005_1](https://user-images.githubusercontent.com/69315126/206860081-e461892d-6a5a-4518-9f52-5f73e212afa8.jpg)
Here is the tweaked tmd if you want to do a diff on it to see the alterations
[wilga_tmd.zip](https://github.com/krzysk1/wilga/files/10200276/wilga_tmd.zip)

**Comment by krzysk1** [comment]
I have search resources and 4 degrees is most likely correct for incidence  so I left  0.06981 for all sections. I have tidied up the code and removed the redundant wing entries from the code.

BTW new aerowings format was introduced with AFS4 and it would be good to convert old aerowing to the new structure for aerowing2. This is recommended for aircraft that have also have slats as wilga.

**Comment by jayeye2011** [comment]
Do you have a link to any updated FS 4 documentation other than the aerofly
wiki. The wiki is pretty unclear if FS 2 or FS 4 and its hard to find all
the TMD sections as the hyperlinks do not cover all the sections.

**Comment by krzysk1** [comment]
Nothing more detailed.  But you can check also https://www.aerofly-sim.de/codesnippets   - Small search engine that allows you to quickly find pretty much all code snippets for the tmd file of an aircraft for the Aerofly FS 2.
